### ISSUE TITLE
Some new words for surface models.

### ISSUE THREAD

**Issue by inventor7777** [EdgeTX/edgetx-sdcard-sounds#113]
Hi all! I would like to see some new English sounds for surface models added. Some I can think of right away include:

"drift mode on"
"drift mode off"
"gyro enabled"
"gyro disabled"
"launch control active"
"wet mode enabled"
"normal mode"
"max gyro"
"max assistance"
"overheating"
"boost mode"

If these sounds are released I'll verify the sound quality and pronunciation on my MT12.

**Comment by inventor7777** [comment]
@pfeerick can you also add “overheating” and “motor overheating” when you get a moment? I don’t see it in the release. Sorry to keep bothering you :)

**Comment by pfeerick** [comment]
No problem... done.

**Comment by inventor7777** [comment]
Thank you so much! I really appreciate that :)
