### ISSUE TITLE
Add surface drive mode sounds (EN)

### ISSUE THREAD

**Issue by inventor7777** [EdgeTX/edgetx-sdcard-sounds#123]
Hi all!

I have some suggestions for some surface driving modes that will be useful when setting up power modes, etc.

**“Bash Mode”
“Race Mode”
“Chill Mode”
“Trainer Mode”
“Speed Mode”** _(I know this sounds similar to “High Speed Mode Active”, but it fits better without the “Active” imo)_
**“City Mode”
“Cruise Mode”**

Hopefully these can be implemented! If they’re implemented, I can help listen to the Ryan version as that’s what I use on my radios.

(Also, is there any word on my suggestions in #118?)

**Comment by pfeerick** [comment]
Someday soon :tm: (probably sooner now that you remind me of the issue ;) )
