### ISSUE TITLE
Catalan Languaje

### ISSUE THREAD

**Issue by Xavitorradas** [EdgeTX/edgetx-sdcard-sounds#15]
I'd like to use Catalan languaje in my TX16S. Meanwhile I have saved with my voice some sounds and changed them in 'es' sound folder and system ( not all changed an some else added ).
  How can I implement 'ca' languaje in EdgeTX ?
  Catalan is one of the 4 oficial languajes in Spain ( Castillian/Spanish, Catalan, Vasque and Galaic ) and has about 10 million of users in the world ( Also ANDORRA ).
  Thanks in advance
[voices.zip](https://github.com/EdgeTX/edgetx-sdcard-sounds/files/8215548/voices.zip)
.

**Comment by pfeerick** [comment]
Would require changes both to the radio firmware to know about another language, as well as to be included here as another language pack.

**Comment by Xavitorradas** [comment]
Meanwhile amb using ES folder with my catalan voice. Thanks

**Comment by pfeerick** [comment]
You may also be interested in this when it merges ;) https://github.com/EdgeTX/edgetx-sdcard-sounds/pull/22
