### ISSUE TITLE
Wrong hello.wav phrase in RU voice pack

### ISSUE THREAD

**Issue by dkrvnkv** [EdgeTX/edgetx-sdcard-sounds#31]
Russian neuro voice dont prounences EdgeTX word correct. Its sounds like Edjix. For correct prounences by neuro voice need use phrase "Добро пожаловать в Эдж Ти Экс" insted of "Добро пожаловать в EdgeTX".

**Comment by pfeerick** [comment]
Thanks for that. The correction has been made, and will be included the next time I regenerate the audio files.
