### ISSUE TITLE
Include sounds.json as a release asset

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx-sdcard-sounds#34]
The file in the code directory reflects the pre-release build and not necessarily Latest or older releases.
This makes automating the installation of releases more challenging such as when using the sounds.json file for displaying available language packs for older releases. Then if chosen pack does not exist handling the error situation.

**Comment by pfeerick** [comment]
Sounds good... so just the file as part of the release, it doesn't need to be in the zips? I can retroactively add that to the say the last two releases then also.

**Comment by elecpower** [comment]
Yes a separate asset file uncompressed.

**Comment by pfeerick** [comment]
Ok, I've added to both the last release and pre-release. I'll make changes to the release action to finish this off properly so will close the issue through that once that's done.

**Comment by elecpower** [comment]
Thanks. I'll mod the updates PR.
