### ISSUE TITLE
Malformed sounds.json in release 2.5.3 assets

### ISSUE THREAD

**Issue by elecpower** [EdgeTX/edgetx-sdcard-sounds#40]
Qt cannot convert to a json document as it needs to have the comma after the last entry removed (see below)
    {
        "language": "zh-CN",
        "name": "Chinese Female",
        "description": "Chinese Female Voice",
        "directory": "cn"
    }, <<<<<<<------------ THIS ONE
]

Note: Latest Voice Pack and Preliminary 2.7.0 are okay

**Comment by pfeerick** [comment]
Thanks, fixed :)
