### ISSUE TITLE
a couple of sound requests

### ISSUE THREAD

**Issue by jawz101** [EdgeTX/edgetx-sdcard-sounds#67]
a sound for Betaflight's Acro Trainer flight mode

Blackbox erase Betaflight mode.  I have a 3-state switch that I have do nothing when it's up, then mid it's set to enable blackbox & when it's all the way down it erases the Blackbox.

**Comment by pfeerick** [comment]
So what exactly do you want to say for each? ;)

**Comment by jawz101** [comment]
"Acro Trainer mode"
"Blackbox erase"

**Comment by pfeerick** [comment]
Since there is already "blackbox active" -> "blkact.wav", I'm thinking 
- "blackbox erase" -> "blkers.wav" 
- "acro trainer mode" -> "actnmd.wav"
