### ISSUE TITLE
de: long silent phase after spoken text

### ISSUE THREAD

**Issue by mha1** [EdgeTX/edgetx-sdcard-sounds#68]
en: about 0.15s silence after spoken text
de: about 0.8s silence after spoken text - this makes german SF play value veeerrrryyy sloooowwww

A played value of 23.7 Volt will take about 2-3 seconds for en, but about 6-7 seconds for de. Please adjust the silent phase accordingly.

Here's a comparison of the en/0023.wav vs de/0023.wav:

![image](https://github.com/EdgeTX/edgetx-sdcard-sounds/assets/5615068/1a276ca1-36b1-4615-b4e1-0370d3397937)

**Comment by pfeerick** [comment]
Is this the release files, or the repo files... as the repo files are the initial source files - they're trimmed as part of the release step in `release.sh`

**Comment by mha1** [comment]
good point - this is the repo files
