### ISSUE TITLE
request sounds for Camera Control

### ISSUE THREAD

**Issue by jawz101** [EdgeTX/edgetx-sdcard-sounds#70]
I have a Runcam Thumb Pro which supports connection to a flight controller to start & stop recording video via Betaflight's support of the Runcam protocol to control cameras.  There are flight modes available in Betaflight to start recording, configure the camera, or enable WiFi on a camera (the thumb doesn't have WiFi but I believe others do.)

Request sounds to say things like:
"camera power button" or "camera/video/recording start/begin"

"camera change mode"
![image](https://github.com/EdgeTX/edgetx-sdcard-sounds/assets/14151703/1d8c1f7c-4273-4d30-8923-387cadf35fb9)

**Comment by pfeerick** [comment]
Will something like this do? Limitd to 6 leter filenames atm for non-system sounds, so hopefully these make sense.
```csv
"String ID","Source text","Translation","Context","Path","Filename"
"443","Camera wifi button","Camera wifi button","camera","","cwifi.wav"
"444","Camera power button","Camera power button","camera","","cpower.wav"
"445","Camera change mode","Camera change mode","camera","","cmode.wav"
"444","Camera start","Camera start","camera","","cstart.wav"
"445","Camera stop","Camera stop","camera","","cstop.wav"
```

**Comment by jawz101** [comment]
Those are great.
I might also consider additional non-specific phrases such as "recording started" "recording stopped"
That could be applicable to blackbox recording or video recording (considering I'd also requested blackbox recording phrases it makes me think generic phrasing might apply to users' various scenarios.
