### ISSUE TITLE
Yaapu "Fly by wire a flight mode" mispronounciation

### ISSUE THREAD

**Issue by lopsided98** [EdgeTX/edgetx-sdcard-sounds#79]
The Yaapu "Fly by wire a flight mode" message (`flybywirea.wav`) is pronounced as if the "a" is part of "wire", rather than being pronounced separately as a letter. "Fly by wire b flight mode" is pronounced correctly. Perhaps capitalizing A or some other minor change would get the TTS to produce the correct result.

**Comment by pfeerick** [comment]
Unfortunately not that simple it seems... I seem to be able to get it to exaggerate the sound more without having to resort to changing the language model used entirely, but it's not quite right for all the EN dialects... i.e. what seems to work better for one can mess up another. But certainly an improvement on the current model... there is at least a pause and more exaggerated pronunciation of the letter now.
