### ISSUE TITLE
Default Azure Voice for English?

### ISSUE THREAD

**Issue by glieb716** [EdgeTX/edgetx-sdcard-sounds#90]
I got the Azure Speech CLI set up on my machine to generate some custom sounds and dink around with the internal sounds. I was generating some GB and US English and non of the female voices seem like the one used in the sound pack. What is the default method and voice used for generating english? Thanks!

**Comment by pfeerick** [comment]
The default voice being used is en-IE-EmilyNeural. To see all of them, have a look at https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/main/generate.sh

**Comment by glieb716** [comment]
closing now *salute*
